// resources/js/Pages/Leader/penanganan/Penanganan-edit.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Canvas, Circle, FabricImage, Rect } from 'fabric'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from '@/components/ui/tooltip'
import LeaderLayout from '@/Layouts/LeaderLayout.vue'
import { useForm, Head } from '@inertiajs/vue3'
import DropZone from '@/Components/DropZone.vue'
import { assetUrl, route } from '@tunbudi06/inertia-route-helper'
import { maxChartTitleLength } from '$/Pages/Leader/KytParameter.ts'
import { toBlob } from 'html-to-image'
import { penangananupdate } from '$routes/leader'
import { toast } from 'vue-sonner'

const props = defineProps({
  kyt: { type: Object, default: null },
  penanganan: { type: Object, default: null },
})

const form = useForm({
  title: props.penanganan?.penanganan_title || '',
  foto_path: null,
  result_path: null,
})

const canvasEl = ref(null)
const previewContainerEl = ref(null)
let canvas = null
const history = ref([])
const redoStack = ref([])
const isLoadingState = ref(false)
const cropRect = ref(null)
const penangananUrlImage = ref('')
const strokeSize = ref(4)

function saveState() {
  if (!canvas || isLoadingState.value) return
  const j = JSON.stringify(canvas.toJSON())
  history.value = [...history.value, j]
  if (history.value.length > 30) history.value = history.value.slice(1)
  redoStack.value = []
}

function undo() {
  if (!canvas || history.value.length === 0) return
  isLoadingState.value = true
  redoStack.value = [...redoStack.value, JSON.stringify(canvas.toJSON())]
  const ps = history.value.pop()
  canvas.loadFromJSON(JSON.parse(ps)).then(() => { canvas.renderAll(); isLoadingState.value = false })
}

function redo() {
  if (!canvas || redoStack.value.length === 0) return
  isLoadingState.value = true
  history.value = [...history.value, JSON.stringify(canvas.toJSON())]
  const ns = redoStack.value.pop()
  canvas.loadFromJSON(JSON.parse(ns)).then(() => { canvas.renderAll(); isLoadingState.value = false })
}

onMounted(() => {
  if (!canvasEl.value) return
  canvas = new Canvas(canvasEl.value, { selection: true, preserveObjectStacking: true })
  canvas.setDimensions({ width: 1200, height: 600 })
  history.value = [JSON.stringify(canvas.toJSON())]

  // Load existing foto_path if available
  if (props.penanganan?.foto_path) {
    FabricImage.fromURL(assetUrl(props.penanganan.foto_path)).then((img) => {
      const cw = canvas.getWidth(); const ch = canvas.getHeight()
      const sc = Math.min(cw / (img.width || 1), ch / (img.height || 1))
      img.set({ originX: 'left', originY: 'top', scaleX: sc, scaleY: sc, left: (cw - (img.width || 0) * sc) / 2, top: (ch - (img.height || 0) * sc) / 2, selectable: true, evented: true })
      img.setCoords(); canvas.add(img); canvas.renderAll(); saveState()
    })
  }

  canvas.on('object:added', () => { if (!isLoadingState.value) saveState() })
  canvas.on('object:modified', () => { if (!isLoadingState.value) saveState() })
  canvas.on('object:removed', () => { if (!isLoadingState.value) saveState() })
})

onUnmounted(() => canvas?.dispose())

function loadImage(file) {
  if (!file || !canvas) return
  const reader = new FileReader()
  reader.onload = () => {
    FabricImage.fromURL(reader.result).then((img) => {
      const cw = canvas.getWidth(); const ch = canvas.getHeight()
      const sc = Math.min(cw / (img.width || 1), ch / (img.height || 1))
      img.set({ originX: 'left', originY: 'top', scaleX: sc, scaleY: sc, left: (cw - (img.width || 0) * sc) / 2, top: (ch - (img.height || 0) * sc) / 2, hasControls: true, selectable: true, evented: true, hasBorders: true })
      img.setCoords(); canvas.add(img); canvas.setActiveObject(img); canvas.renderAll(); saveState()
    })
  }
  reader.readAsDataURL(file)
}

function handleFilesSelect(e) { e.acceptedFiles.forEach(f => loadImage(f)) }

function addHighlightRed() { if (canvas) canvas.add(new Rect({ left: 100, top: 100, width: 120, height: 60, fill: 'transparent', stroke: '#EF4444', strokeWidth: strokeSize.value, cornerColor: '#EF4444' })) }
function addHighlightYellow() { if (canvas) canvas.add(new Rect({ left: 100, top: 100, width: 120, height: 60, fill: 'transparent', stroke: '#FACC15', strokeWidth: strokeSize.value, cornerColor: '#FACC15' })) }
function addCircle() { if (canvas) canvas.add(new Circle({ left: 150, top: 150, radius: 40, fill: 'transparent', stroke: 'red', strokeWidth: strokeSize.value })) }
function removeSelected() { if (canvas) { const o = canvas.getActiveObject(); if (o) { canvas.remove(o); saveState() } } }
function bringToFront() { if (canvas) { const o = canvas.getActiveObject(); if (o) { canvas.bringObjectToFront(o); canvas.renderAll(); saveState() } } }
function bringForward() { if (canvas) { const o = canvas.getActiveObject(); if (o) { canvas.bringObjectForward(o); canvas.renderAll(); saveState() } } }
function sendBackward() { if (canvas) { const o = canvas.getActiveObject(); if (o) { canvas.sendObjectBackwards(o); canvas.renderAll(); saveState() } } }
function sendToBack() { if (canvas) { const o = canvas.getActiveObject(); if (o) { canvas.sendObjectToBack(o); canvas.renderAll(); saveState() } } }

function startCrop() {
  if (cropRect.value || !canvas) return
  const cw = canvas.getWidth(); const ch = canvas.getHeight()
  const rect = new Rect({ left: (cw - 300) / 2, top: (ch - 200) / 2, width: 300, height: 200, fill: 'rgba(0,0,0,0.5)', stroke: '#FFFFFF', strokeWidth: 3, strokeDashArray: [10, 5], hasRotatingPoint: false, cornerColor: '#FFFFFF', cornerSize: 12, transparentCorners: false, cornerStrokeColor: '#000000', borderColor: '#FFFFFF' })
  canvas.add(rect); canvas.bringObjectToFront(rect); canvas.setActiveObject(rect); canvas.renderAll()
  cropRect.value = rect
}

function applyCrop() {
  if (!cropRect.value || !canvas) return
  const r = cropRect.value.getBoundingRect()
  const objs = canvas.getObjects().filter(o => o !== cropRect.value)
  const rm = []
  objs.forEach(o => { const b = o.getBoundingRect(); if (!(b.left + b.width < r.left || b.left > r.left + r.width || b.top + b.height < r.top || b.top > r.top + r.height)) rm.push(o) })
  canvas.remove(cropRect.value); cropRect.value = null; canvas.renderAll()
  const du = canvas.toDataURL({ left: r.left, top: r.top, width: r.width, height: r.height, multiplier: 1, format: 'png' })
  rm.forEach(o => canvas.remove(o))
  FabricImage.fromURL(du).then((img) => {
    const cw = canvas.getWidth(); const ch = canvas.getHeight(); const sc = Math.min(cw / (img.width || 1), ch / (img.height || 1), 1)
    img.set({ originX: 'left', originY: 'top', scaleX: sc, scaleY: sc, left: (cw - (img.width || 0) * sc) / 2, top: (ch - (img.height || 0) * sc) / 2, hasControls: true, selectable: true, evented: true, hasBorders: true })
    img.setCoords(); canvas.add(img); canvas.setActiveObject(img); canvas.renderAll(); saveState()
  })
}

async function exportImage() {
  if (!canvas) return
  const blob = await canvas.toBlob({ format: 'png', multiplier: 1, enableRetinaScaling: true })
  if (!blob) return
  form.foto_path = new File([blob], `penanganan-${Date.now()}.png`, { type: 'image/png' })
  penangananUrlImage.value = URL.createObjectURL(blob)
}

async function generatePreviewThumbnail() {
  if (!previewContainerEl.value) return false
  try {
    await new Promise(r => setTimeout(r, 300))
    const imgs = previewContainerEl.value.querySelectorAll('img')
    const orig = new Map()
    for (const img of Array.from(imgs)) {
      if (img.src.startsWith('blob:')) {
        orig.set(img, img.src)
        try { const r = await fetch(img.src); const b = await r.blob(); const du = await new Promise(r => { const fr = new FileReader(); fr.onloadend = () => r(fr.result); fr.readAsDataURL(b) }); img.src = du } catch (e) { console.warn(e) }
      }
    }
    await new Promise(r => setTimeout(r, 100))
    const blob = await toBlob(previewContainerEl.value, { quality: 1.0, pixelRatio: 3, cacheBust: true, skipAutoScale: false, backgroundColor: '#ffffff' })
    for (const [img, src] of orig.entries()) { img.src = src }
    if (!blob) throw new Error('Failed')
    form.result_path = new File([blob], `penanganan-preview-${Date.now()}.png`, { type: 'image/png' })
    return true
  } catch (e) { console.error(e); alert('Gagal membuat preview'); return false }
}

async function submitForm(e) {
  e.preventDefault()
  const ok = await generatePreviewThumbnail()
  if (!ok) return
  form.submit(route(penangananupdate({ id: props.penanganan.id })), {
    preserveScroll: true,
    onSuccess: () => toast.success('Penanganan berhasil diperbarui!'),
    onError: (err) => console.error(err),
  })
}

function handleKeydown(e) {
  if (!canvas) return
  if (e.ctrlKey && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); return }
  if ((e.ctrlKey && e.key === 'y') || (e.ctrlKey && e.shiftKey && e.key === 'z')) { e.preventDefault(); redo(); return }
  if ((e.key === 'Delete' || e.key === 'Backspace') && canvas.getActiveObject()) { e.preventDefault(); removeSelected(); return }
}

onMounted(() => window.addEventListener('keydown', handleKeydown))
onUnmounted(() => window.removeEventListener('keydown', handleKeydown))
</script>

<template>
  <Head><title>Edit Penanganan - Leader Dashboard</title></Head>

  <LeaderLayout>
    <div class="space-y-6">
      <div>
        <h3 class="font-bold text-3xl tracking-tight">Edit Penanganan</h3>
        <span class="text-muted-foreground mt-1">Edit penanganan untuk kiken yochi training</span>
      </div>

      <!-- KYT Preview -->
      <Card>
        <CardHeader class="space-y-0">
          <CardTitle class="w-full text-center font-bold text-3xl">KYT Preview</CardTitle>
          <CardDescription class="w-full text-center">Berikut adalah preview KYT yang telah dibuat</CardDescription>
        </CardHeader>
        <CardContent>
          <div class="overflow-x-auto">
            <div class="relative mx-auto max-w-full" style="width: 1280px; height: 680px;">
              <img :src="assetUrl(kyt?.result_path)" alt="KYT Background" class="rounded-lg border border-border object-contain w-full h-full" />
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Form -->
      <Card>
        <CardHeader class="space-y-0">
          <CardTitle class="w-full text-center font-bold text-3xl">Form Edit Penanganan</CardTitle>
          <CardDescription class="w-full text-center">Edit form penanganan pada KYT</CardDescription>
        </CardHeader>
        <CardContent>
          <div class="grid gap-4">
            <div class="grid gap-2">
              <Label for="title">Masukkan Title:
                <span class="text-xs text-muted-foreground ml-2">({{ form.title.length }}/{{ maxChartTitleLength }})</span>
              </Label>
              <Input id="title" v-model="form.title" :maxlength="maxChartTitleLength" placeholder="Masukkan Title" />
            </div>
            <div class="grid gap-2">
              <Label for="foto_path">Upload Gambar Penanganan (kosongkan jika tidak ingin mengganti):</Label>
              <DropZone @drop="handleFilesSelect" />
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Canvas Editor -->
      <Card>
        <CardContent class="p-4">
          <div class="flex gap-2 pb-4 flex-wrap">
            <div class="flex items-center gap-2">
              <Label for="strokeSize">Stroke Size:</Label>
              <Input id="strokeSize" type="number" min="1" max="20" v-model.number="strokeSize" class="w-20" />
            </div>
            <Button variant="outline" @click="addHighlightRed" class="justify-start"><span class="inline-block w-3 h-3 rounded-sm mr-2 bg-red-500"></span>Highlight Red</Button>
            <Button variant="outline" @click="addHighlightYellow" class="justify-start"><span class="inline-block w-3 h-3 rounded-sm mr-2 bg-yellow-500"></span>Highlight Yellow</Button>
            <Button variant="outline" @click="addCircle" class="justify-start">🔴 Circle</Button>
            <Button variant="outline" @click="removeSelected" class="justify-start">🗑️ Remove Selected</Button>
            <Button variant="outline" @click="bringToFront" class="justify-start">⏫ Bring To Front</Button>
            <Button variant="outline" @click="bringForward" class="justify-start">🔼 Bring Forward</Button>
            <Button variant="outline" @click="sendBackward" class="justify-start">🔽 Send Backward</Button>
            <Button variant="outline" @click="sendToBack" class="justify-start">⏬ Send To Back</Button>
            <Button variant="outline" @click="startCrop" class="justify-start">✂️ Crop</Button>
            <Button variant="outline" @click="applyCrop" class="justify-start">✅ Apply Crop</Button>
          </div>
          <div class="overflow-x-auto overflow-y-hidden bg-muted/30 p-4 rounded-lg touch-pan-x">
            <div class="mx-auto bg-white" style="width: 1200px; height: 600px;">
              <canvas ref="canvasEl" class="border border-border rounded-lg shadow-sm" style="width: 1200px; height: 600px;"></canvas>
            </div>
          </div>
          <div class="flex flex-col sm:flex-row gap-2 mt-4">
            <Button variant="outline" @click="undo" class="flex-1">↩️ Undo</Button>
            <Button variant="outline" @click="redo" class="flex-1">↪️ Redo</Button>
            <Button @click="exportImage" class="flex-1">💾 Lihat Hasil</Button>
          </div>
        </CardContent>
      </Card>

      <!-- Preview -->
      <Card>
        <CardHeader>
          <CardTitle>Kiken Yochi Training - Preview</CardTitle>
          <CardDescription>
            <template v-if="penangananUrlImage">Hasil gambar yang telah disimpan</template>
            <template v-else>Klik "💾 Lihat Hasil" untuk melihat hasil</template>
          </CardDescription>
        </CardHeader>
        <CardContent class="p-4">
          <div class="overflow-x-auto">
            <div ref="previewContainerEl" class="relative mx-auto w-300 h-170 bg-pink-200 border-4 p-2 border-black flex items-center justify-center">
              <template v-if="penangananUrlImage">
                <div class="absolute top-0 left-0 w-full flex items-center max-w-300 justify-center pt-2">
                  <span class="font-bold text-2xl leading-tight text-center text-black uppercase">{{ form.title }}</span>
                </div>
                <div class="absolute inset-0 left-0 top-16 w-300 h-150">
                  <img :src="penangananUrlImage" alt="Hasil editing KYT" class="rounded shadow-lg w-full h-full" />
                </div>
              </template>
              <template v-else>
                <span class="font-bold text-2xl leading-tight text-center max-w-300 text-wrap text-black uppercase">{{ form.title || 'Masukkan judul untuk preview' }}</span>
              </template>
            </div>
          </div>
          <div class="mt-4">
            <Button @click="submitForm" class="w-full" :disabled="form.processing || !form.title">
              <template v-if="form.processing">Menyimpan...</template>
              <template v-else-if="form.title">Simpan Perubahan Penanganan</template>
              <template v-else>Tambahkan judul terlebih dahulu</template>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  </LeaderLayout>
</template>

<style scoped>
canvas { touch-action: none; }
</style>

// resources/js/Pages/Leader/penanganan/Penanganan-edit.svelte
<script lang="ts">
    import LeaderLayout from "$/Layouts/LeaderLayout.svelte";
    import * as Card from "$shadcn/components/ui/card/index.ts";
    import * as Field from "$shadcn/components/ui/field/index.js";
    import * as Tooltip from "$shadcn/components/ui/tooltip/index.js";
    import {assetUrl, route} from "@tunbudi06/inertia-route-helper";
    import {useForm} from "@inertiajs/svelte";
    import {Input} from "$shadcn/components/ui/input";
    import {Button} from "$shadcn/components/ui/button";
    import {Canvas, Circle, FabricImage, Rect} from "fabric";
    import Dropzone, { type DropzoneEvent } from 'svelte-dropzone-runes';
    import {onMount} from "svelte";
    import {maxChartTitleLength} from "$/Pages/Leader/KytParameter.ts";
    import {toBlob} from "html-to-image";
    import {penangananupdate} from "$routes/leader";
    import {toast} from "svelte-sonner";

    let { kyt, penanganan } = $props();

    function handleFilesSelect(e: DropzoneEvent<File>) {
        e.acceptedFiles.forEach((file: File) => {
            loadImage(file);
        });
    }

    const form = useForm({
        title: penanganan.penanganan_title || '',
        foto_path: null as File | null,
        result_path: null as File | null,
    });

    let canvasEl = $state<HTMLCanvasElement>();
    let previewContainerEl = $state<HTMLDivElement>();
    let canvas = $state<Canvas>();
    let history = $state<string[]>([]);
    let redoStack = $state<string[]>([]);
    let isLoadingState = $state(false);
    let cropRect = $state<Rect | null>(null);
    let penangananUrlImage = $state<string>("");
    let strokeSize = $state<number>(4);

    function saveState() {
        if (!canvas || isLoadingState) return;
        const json = JSON.stringify(canvas.toJSON());
        history = [...history, json];
        if (history.length > 30) history = history.slice(1);
        redoStack = [];
    }

    function undo() {
        if (!canvas || history.length === 0) return;
        isLoadingState = true;
        const currentState = JSON.stringify(canvas.toJSON());
        redoStack = [...redoStack, currentState];
        const previousState = history[history.length - 1];
        history = history.slice(0, -1);
        canvas.loadFromJSON(JSON.parse(previousState)).then(() => {
            canvas!.renderAll();
            isLoadingState = false;
        });
    }

    function redo() {
        if (!canvas || redoStack.length === 0) return;
        isLoadingState = true;
        const currentState = JSON.stringify(canvas.toJSON());
        history = [...history, currentState];
        const nextState = redoStack[redoStack.length - 1];
        redoStack = redoStack.slice(0, -1);
        canvas.loadFromJSON(JSON.parse(nextState)).then(() => {
            canvas!.renderAll();
            isLoadingState = false;
        });
    }

    onMount(() => {
        if (!canvasEl) return;

        canvas = new Canvas(canvasEl, {
            selection: true,
            preserveObjectStacking: true
        });

        canvas.setDimensions({ width: 1200, height: 600 });
        history = [JSON.stringify(canvas.toJSON())];

        // Load existing foto_path onto canvas if available
        if (penanganan.foto_path) {
            const existingUrl = assetUrl(penanganan.foto_path);
            FabricImage.fromURL(existingUrl).then((img) => {
                const canvasWidth = canvas!.getWidth();
                const canvasHeight = canvas!.getHeight();
                const scaleX = canvasWidth / (img.width || 1);
                const scaleY = canvasHeight / (img.height || 1);
                const scale = Math.min(scaleX, scaleY);
                const scaledWidth = (img.width || 0) * scale;
                const scaledHeight = (img.height || 0) * scale;
                img.set({
                    originX: "left",
                    originY: "top",
                    scaleX: scale,
                    scaleY: scale,
                    left: (canvasWidth - scaledWidth) / 2,
                    top: (canvasHeight - scaledHeight) / 2,
                    selectable: true,
                    evented: true,
                });
                img.setCoords();
                canvas!.add(img);
                canvas!.renderAll();
                saveState();
            });
        }

        canvas.on("object:added", () => { if (!isLoadingState) saveState(); });
        canvas.on("object:modified", () => { if (!isLoadingState) saveState(); });
        canvas.on("object:removed", () => { if (!isLoadingState) saveState(); });

        return () => { canvas?.dispose(); };
    });

    function loadImage(file: File) {
        if (!file || !canvas) return;
        const reader = new FileReader();
        reader.onload = () => {
            FabricImage.fromURL(reader.result as string).then((img) => {
                const canvasWidth = canvas!.getWidth();
                const canvasHeight = canvas!.getHeight();
                const scaleX = canvasWidth / (img.width || 1);
                const scaleY = canvasHeight / (img.height || 1);
                const scale = Math.min(scaleX, scaleY);
                const scaledWidth = (img.width || 0) * scale;
                const scaledHeight = (img.height || 0) * scale;
                img.set({
                    originX: "left",
                    originY: "top",
                    scaleX: scale,
                    scaleY: scale,
                    left: (canvasWidth - scaledWidth) / 2,
                    top: (canvasHeight - scaledHeight) / 2,
                    selectable: true,
                    evented: true,
                    hasControls: true,
                    hasBorders: true,
                });
                img.setCoords();
                canvas!.add(img);
                canvas!.setActiveObject(img);
                canvas!.renderAll();
                saveState();
            });
        };
        reader.readAsDataURL(file);
    }

    function addHighlightYellow() {
        if (!canvas) return;
        canvas.add(new Rect({
            left: 100, top: 100, width: 120, height: 60,
            fill: "transparent", stroke: "#FACC15", strokeWidth: strokeSize, cornerColor: "#FACC15"
        }));
    }

    function addHighlightRed() {
        if (!canvas) return;
        canvas.add(new Rect({
            left: 100, top: 100, width: 120, height: 60,
            fill: "transparent", stroke: "#EF4444", strokeWidth: strokeSize, cornerColor: "#EF4444"
        }));
    }

    function addCircle() {
        if (!canvas) return;
        canvas.add(new Circle({
            left: 150, top: 150, radius: 40,
            fill: "transparent", stroke: "red", strokeWidth: strokeSize
        }));
    }

    function startCrop() {
        if (cropRect || !canvas) return;
        const canvasWidth = canvas.getWidth();
        const canvasHeight = canvas.getHeight();
        const cropWidth = 300;
        const cropHeight = 200;
        cropRect = new Rect({
            left: (canvasWidth - cropWidth) / 2,
            top: (canvasHeight - cropHeight) / 2,
            width: cropWidth,
            height: cropHeight,
            fill: "rgba(0,0,0,0.5)",
            stroke: "#FFFFFF",
            strokeWidth: 3,
            strokeDashArray: [10, 5],
            hasRotatingPoint: false,
            cornerColor: "#FFFFFF",
            cornerSize: 12,
            transparentCorners: false,
            cornerStrokeColor: "#000000",
            borderColor: "#FFFFFF"
        });
        canvas.add(cropRect);
        canvas.bringObjectToFront(cropRect);
        canvas.setActiveObject(cropRect);
        canvas.renderAll();
    }

    function applyCrop() {
        if (!cropRect || !canvas) return;
        const rect = cropRect.getBoundingRect();
        const allObjects = canvas.getObjects().filter(obj => obj !== cropRect);
        const objectsToRemove: any[] = [];
        allObjects.forEach(obj => {
            const objBounds = obj.getBoundingRect();
            const intersects = !(
                objBounds.left + objBounds.width < rect.left ||
                objBounds.left > rect.left + rect.width ||
                objBounds.top + objBounds.height < rect.top ||
                objBounds.top > rect.top + rect.height
            );
            if (intersects) objectsToRemove.push(obj);
        });
        canvas.remove(cropRect);
        cropRect = null;
        canvas.renderAll();
        const dataUrl = canvas.toDataURL({
            left: rect.left, top: rect.top, width: rect.width, height: rect.height,
            multiplier: 1, format: "png"
        });
        objectsToRemove.forEach(obj => canvas!.remove(obj));
        FabricImage.fromURL(dataUrl).then((img) => {
            const canvasWidth = canvas!.getWidth();
            const canvasHeight = canvas!.getHeight();
            const scale = Math.min(canvasWidth / (img.width || 1), canvasHeight / (img.height || 1), 1);
            const scaledWidth = (img.width || 0) * scale;
            const scaledHeight = (img.height || 0) * scale;
            img.set({
                originX: "left", originY: "top",
                scaleX: scale, scaleY: scale,
                left: (canvasWidth - scaledWidth) / 2,
                top: (canvasHeight - scaledHeight) / 2,
                selectable: true, evented: true,
                hasControls: true, hasBorders: true,
            });
            img.setCoords();
            canvas!.add(img);
            canvas!.setActiveObject(img);
            canvas!.renderAll();
            saveState();
        });
    }

    async function exportImage() {
        if (!canvas) return;
        const blob = await canvas.toBlob({ format: "png", multiplier: 1, enableRetinaScaling: true });
        if (!blob) return;
        const timestamp = new Date().getTime();
        $form.foto_path = new File([blob], `kyt-edited-${timestamp}.png`, { type: "image/png" });
        penangananUrlImage = URL.createObjectURL(blob);
    }

    function bringForward() {
        if (!canvas) return;
        const obj = canvas.getActiveObject();
        if (obj) { canvas.bringObjectForward(obj); canvas.renderAll(); saveState(); }
    }

    function sendBackward() {
        if (!canvas) return;
        const obj = canvas.getActiveObject();
        if (obj) { canvas.sendObjectBackwards(obj); canvas.renderAll(); saveState(); }
    }

    function bringToFront() {
        if (!canvas) return;
        const obj = canvas.getActiveObject();
        if (obj) { canvas.bringObjectToFront(obj); canvas.renderAll(); saveState(); }
    }

    function sendToBack() {
        if (!canvas) return;
        const obj = canvas.getActiveObject();
        if (obj) { canvas.sendObjectToBack(obj); canvas.renderAll(); saveState(); }
    }

    function removeSelected() {
        if (!canvas) return;
        const obj = canvas.getActiveObject();
        if (obj) { canvas.remove(obj); saveState(); }
    }

    function keyPressFunction(event: KeyboardEvent) {
        if (!canvas) return;
        if (event.ctrlKey && event.key === 'z' && !event.shiftKey) {
            event.preventDefault(); undo(); return;
        }
        if ((event.ctrlKey && event.key === 'y') || (event.ctrlKey && event.shiftKey && event.key === 'z')) {
            event.preventDefault(); redo(); return;
        }
        if ((event.key === 'Delete' || event.key === 'Backspace') && canvas.getActiveObject()) {
            event.preventDefault(); removeSelected(); return;
        }
    }

    async function generatePreviewThumbnail() {
        if (!previewContainerEl) return false;
        try {
            await new Promise(resolve => setTimeout(resolve, 300));
            const images = previewContainerEl.querySelectorAll('img');
            const originalSrcs: Map<HTMLImageElement, string> = new Map();
            for (const img of Array.from(images)) {
                if (img.src.startsWith('blob:')) {
                    originalSrcs.set(img, img.src);
                    try {
                        const response = await fetch(img.src);
                        const blob = await response.blob();
                        const dataUrl = await new Promise<string>((resolve) => {
                            const reader = new FileReader();
                            reader.onloadend = () => resolve(reader.result as string);
                            reader.readAsDataURL(blob);
                        });
                        img.src = dataUrl;
                    } catch (err) {
                        console.warn('Failed to convert blob URL:', err);
                    }
                }
            }
            await new Promise(resolve => setTimeout(resolve, 100));
            const blob = await toBlob(previewContainerEl, {
                quality: 1.0, pixelRatio: 3, cacheBust: true,
                skipAutoScale: false, backgroundColor: '#ffffff',
            });
            for (const [img, src] of originalSrcs.entries()) { img.src = src; }
            if (!blob) throw new Error('Failed to generate blob');
            const timestamp = new Date().getTime();
            $form.result_path = new File([blob], `kyt-preview-${timestamp}.png`, { type: "image/png" });
            return true;
        } catch (error) {
            console.error('Error generating preview thumbnail:', error);
            alert('Gagal membuat thumbnail preview. Silakan coba lagi.');
            return false;
        }
    }

    async function submitForm(event: Event) {
        event.preventDefault();
        const success = await generatePreviewThumbnail();
        if (!success) return;

        $form.submit(route(penangananupdate({ id: penanganan.id })), {
            preserveScroll: true,
            onSuccess: () => {
                toast.success('Penanganan berhasil diperbarui!');
            },
            onError: (errors) => {
                console.error('Error updating penanganan:', errors);
            }
        });
    }
</script>

<svelte:head>
    <title>Edit Penanganan - Leader Dashboard</title>
</svelte:head>

<svelte:window onkeydown={keyPressFunction} />

<LeaderLayout>
    <div class="space-y-6">
        <div>
            <h3 class="font-bold text-3xl tracking-tight">Edit Penanganan</h3>
            <span class="text-muted-foreground mt-1">Edit penanganan untuk kiken yochi training</span>
        </div>

        <Card.Root>
            <Card.Header class="space-y-0">
                <Card.Title class="w-full text-center font-bold text-3xl">KYT Preview</Card.Title>
                <Card.Description class="w-full text-center">
                    Berikut adalah preview KYT yang telah dibuat
                </Card.Description>
            </Card.Header>
            <Card.Content>
                <div class="overflow-x-auto">
                    <div class="relative mx-auto max-w-full" style="width: 1280px; height: 680px;">
                        <img
                            src={assetUrl(kyt.result_path)}
                            alt="KYT Background"
                            class="rounded-lg border border-border object-contain w-full h-full"
                        />
                    </div>
                </div>
            </Card.Content>
        </Card.Root>

        <Card.Root>
            <Card.Header class="space-y-0">
                <Card.Title class="w-full text-center font-bold text-3xl">Form Edit Penanganan</Card.Title>
                <Card.Description class="w-full text-center">
                    Edit form penanganan pada KYT
                </Card.Description>
            </Card.Header>
            <Card.Content>
                <Field.Set>
                    <Field.Group>
                        <Field.Field>
                            <Field.Label for="title">Masukkan Title:
                                <span class="text-xs text-muted-foreground ml-2">
                                    ({$form.title.length}/{maxChartTitleLength})
                                </span>
                            </Field.Label>
                            <Input type="text" maxlength={maxChartTitleLength} bind:value={$form.title} id="title" placeholder="Masukkan Title" />
                        </Field.Field>
                        <Field.Field>
                            <Field.Label for="foto_path">Upload Gambar Penanganan (kosongkan jika tidak ingin mengganti):</Field.Label>
                            <Dropzone id="foto_path" multiple onDrop={handleFilesSelect} />
                        </Field.Field>
                    </Field.Group>
                </Field.Set>
            </Card.Content>
        </Card.Root>

        <div class="space-y-6">
            <!-- Canvas Editor -->
            <Card.Root>
                <Card.Content class="p-4">
                    <div class="flex gap-2 pb-4 flex-wrap">
                        <Field.Group class="flex-row">
                            <Tooltip.Root>
                                <Tooltip.Trigger>
                                    <Field.Label for="strokeSize">Stroke Size:</Field.Label>
                                    <Input type="number" id="strokeSize" min="1" max="20" bind:value={strokeSize} class="w-20" />
                                </Tooltip.Trigger>
                                <Tooltip.Content><p>Ukuran garis</p></Tooltip.Content>
                            </Tooltip.Root>
                        </Field.Group>

                        <Button variant="outline" onclick={addHighlightRed} class="justify-start">
                            <span class="inline-block w-3 h-3 rounded-sm mr-2 bg-red-500" aria-hidden="true"></span>
                            Highlight Red
                        </Button>
                        <Button variant="outline" onclick={addHighlightYellow} class="justify-start">
                            <span class="inline-block w-3 h-3 rounded-sm mr-2 bg-yellow-500" aria-hidden="true"></span>
                            Highlight Yellow
                        </Button>
                        <Button variant="outline" onclick={addCircle} class="justify-start">
                            🔴 Circle
                        </Button>
                        <Button variant="outline" onclick={removeSelected} class="justify-start">
                            🗑️ Remove Selected
                        </Button>

                        <div class="border-t border-border my-2"></div>

                        <Button variant="outline" onclick={bringToFront} class="justify-start">⏫ Bring To Front</Button>
                        <Button variant="outline" onclick={bringForward} class="justify-start">🔼 Bring Forward</Button>
                        <Button variant="outline" onclick={sendBackward} class="justify-start">🔽 Send Backward</Button>
                        <Button variant="outline" onclick={sendToBack} class="justify-start">⏬ Send To Back</Button>

                        <div class="border-t border-border my-2"></div>

                        <Button variant="outline" onclick={startCrop} class="justify-start">✂️ Crop</Button>
                        <Button variant="outline" onclick={applyCrop} class="justify-start">✅ Apply Crop</Button>
                    </div>

                    <div class="overflow-x-auto overflow-y-hidden bg-muted/30 p-4 rounded-lg touch-pan-x">
                        <div class="mx-auto bg-white min-w-[1200px]" style="width: 1200px; height: 600px;">
                            <canvas
                                bind:this={canvasEl}
                                class="border border-border rounded-lg shadow-sm"
                                style="width: 1200px; height: 600px;"
                            ></canvas>
                        </div>
                    </div>

                    <div class="flex flex-col sm:flex-row gap-2 mt-4">
                        <Button variant="outline" onclick={undo} class="justify-start flex-1">↩️ Undo</Button>
                        <Button variant="outline" onclick={redo} class="justify-start flex-1">↪️ Redo</Button>
                        <Button onclick={exportImage} class="justify-start flex-1">💾 Lihat Hasil</Button>
                    </div>
                </Card.Content>
            </Card.Root>

            <Card.Root>
                <Card.Header>
                    <Card.Title>Kiken Yochi Training - Preview</Card.Title>
                    <Card.Description>
                        {#if penangananUrlImage}
                            Hasil gambar yang telah disimpan
                        {:else}
                            Klik "💾 Lihat Hasil" untuk melihat hasil gambar di sini
                        {/if}
                    </Card.Description>
                </Card.Header>
                <Card.Content class="p-4">
                    <div class="overflow-x-auto">
                        <div bind:this={previewContainerEl} class="relative mx-auto w-300 h-170 bg-pink-200 border-4 p-2 border-black flex items-center justify-center">
                            {#if penangananUrlImage}
                                <div class="absolute top-0 left-0 w-full flex items-center max-w-300 justify-center pt-2">
                                    <span class="font-bold text-2xl leading-tight text-center text-black uppercase">
                                        {$form.title}
                                    </span>
                                </div>
                                <div class="absolute inset-0 left-0 top-16 w-300 h-150">
                                    <img src={penangananUrlImage} alt="Hasil editing KYT" class="rounded shadow-lg w-full h-full" />
                                </div>
                            {:else}
                                <span class="font-bold text-2xl leading-tight text-center max-w-300 text-wrap text-black uppercase">
                                    {$form.title || 'Masukkan judul untuk preview'}
                                </span>
                            {/if}
                        </div>
                    </div>
                    <div class="mt-4">
                        <Button
                            onclick={submitForm}
                            class="w-full"
                            disabled={$form.processing || !$form.title}
                        >
                            {#if $form.processing}
                                Menyimpan...
                            {:else if $form.title}
                                Simpan Perubahan Penanganan
                            {:else}
                                Tambahkan judul terlebih dahulu
                            {/if}
                        </Button>
                    </div>
                </Card.Content>
            </Card.Root>
        </div>
    </div>
</LeaderLayout>
