// resources/js/Pages/Auth/LoginPage.svelte
<script lang="ts">
    import { Button } from "$shadcn/components/ui/button/index.js";
    import * as Card from "$shadcn/components/ui/card/index.js";
    import {useForm} from "@inertiajs/svelte"
    import {login} from "$routes";
    import {route} from "@tunbudi06/inertia-route-helper";
    import { Input } from "$shadcn/components/ui/input/index.js";
    import {
        FieldGroup,
        Field,
        FieldLabel,
        FieldError,
    } from "$shadcn/components/ui/field/index.js";
    import LoginLayouts from "$/Layouts/LoginLayouts.svelte";
    let form = useForm({
        username: '',
        password: '',
    }).dontRemember('password');

    function onsubmit(e: Event) {
        e.preventDefault();
        $form.submit(route(login()), {
            onSuccess: (e) => {
                console.log('Login successful', e);
            },
        });
    }
</script>

<LoginLayouts>
    <Card.Root class="mx-auto w-full max-w-sm">
        <Card.Header>
            <Card.Title class="text-2xl">Login</Card.Title>
            <Card.Description>Enter your username below to login to your account</Card.Description>
        </Card.Header>
        <Card.Content>
            <form {onsubmit}>
                <FieldGroup>
                    <Field>
                        <FieldLabel for="email">Username</FieldLabel>
                        <Input id="username" bind:value={$form.username} type="text" placeholder="johndoe" required />
                        <FieldError>{$form.errors.username}</FieldError>
                    </Field>
                    <Field>
                        <div class="flex items-center">
                            <FieldLabel for="password">Password</FieldLabel>
                        </div>
                        <Input id="password" bind:value={$form.password} type="password" required />
                        <FieldError>{$form.errors.password}</FieldError>
                    </Field>
                    <Field>
                        <Button type="submit" class="w-full">Login</Button>
                    </Field>
                </FieldGroup>
            </form>
        </Card.Content>
    </Card.Root>
</LoginLayouts>

// resources/js/Pages/Auth/LoginPage.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useForm, Link } from '@inertiajs/vue3'
import { login } from '$routes'
import { route } from '@tunbudi06/inertia-route-helper'
import LoginLayout from '@/Layouts/LoginLayout.vue'
import { ref } from 'vue'

const form = useForm({
  username: '',
  password: '',
})

const errors = form.errors

function onsubmit(e:Event) {
  e.preventDefault()
  form.submit('post', route(login()).url, {
    onSuccess: (res) => {
      console.log('Login successful', res)
    },
  })
}
</script>

<template>
  <LoginLayout>
    <Card class="mx-auto w-full max-w-sm">
      <CardHeader>
        <CardTitle class="text-2xl">Login</CardTitle>
        <CardDescription>Enter your username below to login to your account</CardDescription>
      </CardHeader>
      <CardContent>
        <form @submit="onsubmit">
          <div class="grid gap-4">
            <div class="grid gap-2">
              <Label for="username">Username</Label>
              <Input id="username" v-model="form.username" type="text" placeholder="johndoe" required />
              <p v-if="errors.username" class="text-sm text-red-500">{{ errors.username }}</p>
            </div>
            <div class="grid gap-2">
              <Label for="password">Password</Label>
              <Input id="password" v-model="form.password" type="password" required />
              <p v-if="errors.password" class="text-sm text-red-500">{{ errors.password }}</p>
            </div>
            <Button type="submit" class="w-full" :disabled="form.processing">
              {{ form.processing ? 'Logging in...' : 'Login' }}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  </LoginLayout>
</template>
